# https://help.github.com/en/articles/workflow-syntax-for-github-actions

on: push
name: Windows
jobs:
  verify:
    name: Verify
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
        - windows-latest
        nodejs:
        - 8
        - 10
        - 12
      fail-fast: false
    steps:
    - name: Turn off auto-crlf
      run: git config --global core.autocrlf false
    - name: Checkout source codes
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.nodejs }}
    - name: Output versions
      run: |
        node -v
        npm -v
    - name: Install dependencies
      run: npm ci
    - name: Verify
      run: npm run verify
    - name: Build
      run: npm run build
    - name: Check syntax
      run: |
        ./bin/file-to-stdin README.md cat
        ./bin/stdout-to-file out cat README
